### ISSUE TITLE
Make sliders easier to use

### ISSUE THREAD

**Issue by Faraday-dot-py** [Patribots4738/ScoutingWebsite#4]
This involves:
- Making them bigger
- Be between intervals of 0-10, and snap to those intervals
- Make them look nice

**Comment by GalexY727** [comment]
![image](https://github.com/Patribots4738/ScoutingWebsite/assets/65139378/cdce22f2-dd07-4549-8120-b6f972503502)
This is what 6328's scouting page looks like, and I liked the idea of only having a small range to pick from and the slider snap to that range, in this case, 1-5. I think it would be interesting to see how easily this kind of slider would be implemented, but it is important to consider the value of having a slider that is 0-100 vs 0-5. Would it lead to more consistent data due to the user having to make a more distinct decision? Or would it make data to broad and not unique enough to evaluate upon?

**Comment by Oliver-Cushman** [comment]
I think it might be better to reduce the scale of the sliders a bit as it is a little strange to ask for such a precise rating for something that may be based on somewhat unique criteria for each user.

**Comment by Oliver-Cushman** [comment]
@klaefee If you are still working on this there is a branch ready to go for you to work on.

**Comment by klaefee** [comment]
<img width="290" alt="image" src="https://github.com/Patribots4738/ScoutingWebsite/assets/66997563/300d1523-c870-4f27-9690-9d6e08bcb5fc">
Slider changed from a 0-100 scale to a 1-5 scale, along with adding text to provide a reference for the meaning of the highest value and the lowest value.

**Comment by Oliver-Cushman** [comment]
Looks good, can you make a pull request?
